spring:
  application:
    name: rest-api-with-boot
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  header: Authorization
  prefix: Bearer
  access:
    exp-time: 3600000
    secret: 9d4fJz7E6r1L4jW6p3q8N2k5Y4t2O1b9V6s7X3z9H2c4Q8f1G7
  refresh:
    exp-time: 864000000
    secret: b5m6J2k7H8n3R4e1D9t2S1v5U6p9L3q4P5x7C2a6V8o2B9w3T4
