spring:
  application:
    name: rest-api-with-boot
  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  header: Authorization
  prefix: Bearer
  access-exp-time: 3600000
  refresh-exp-time: 864000000
  secret-access: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  secret-refresh: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855