spring:
  application:
    name: rest-api-with-boot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8

jwt:
  header: Authorization
  prefix: Bearer
  access-token:
    exp-time: 3600000
    secret: 9d4fJz7E6r1L4jW6p3q8N2k5Y4t2O1b9V6s7X3z9H2c4Q8f1G7
  refresh-token:
    exp-time: 864000000
    secret: b5m6J2k7H8n3R4e1D9t2S1v5U6p9L3q4P5x7C2a6V8o2B9w3T4
