spring:
  application:
    name: rest-api-with-boot
  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  header: Authorization
  prefix: Bearer
  access-exp-time: 3600000
  refresh-exp-time: 864000000
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ