= REST API Guide
김동현;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용


////
| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용
////


| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `403 Forbidden`
| 권한 없음.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

// [[overview-hypermedia]]
// == 하이퍼미디어
//
// 본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
// 응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
// 링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.
---
[[resources]]
= 리소스

[[resources-account]]
== 계정 생성 및 탈퇴
계정 생성 및 탈퇴를 위한 리소스이다.

[[resources-account-create]]
=== 회원가입
'POST' 요청을 사용하여 새로운 사용자를 생성할 수 있다.

operation::create-account[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-account-get]]
=== 회원 정보 조회
'GET' 요청을 사용하여 사용자 정보를 조회할 수 있다.

operation::get-account-info[snippets='response-fields,curl-request,http-response']

[[resources-account-delete]]
=== 회원 탈퇴
'DELETE' 요청을 사용하여 사용자를 삭제할 수 있다.
Soft Delete로 처리되며, 회원 탈퇴 시 사용자 정보는 삭제되지 않고,
사용자의 계정 상태를 비활성화 처리한다 및 사용자의 모든 정보는 삭제된다.

operation::delete-account[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-auth]]
== Login, JWT Token
로그인 처리를 통한 토큰 발급 및 토큰 갱신을 위한 리소스이다.

[[resources-auth-login]]
=== 로그인 및 토큰 발급
'POST' 요청을 사용하여 사용자를 인증하고 JWT 토큰을 발급받을 수 있다.

operation::get-access-token[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-auth-refresh]]
=== Refresh 토큰을 이용한 토큰 재발급
'POST' 요청을 사용하여 Refresh 토큰을 이용하여 JWT 토큰을 재발급받을 수 있다.

operation::get-refresh-token[snippets='request-parameters,curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-meeting]]
== 모임
모임 리소스는 모임 만들거나 조회할 때 사용한다.

[[resources-meeting-list]]
=== 모임 리스트 조회

`GET` 요청을 사용하여 서비스의 모든 이벤트를 조회할 수 있다.

operation::get-meeting-list[snippets='response-fields,curl-request,http-response']

[[resources-meeting-create]]
=== 모임 생성

`POST` 요청을 사용해서 새 이벤트를 만들 수 있다.

operation::create-meeting[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-meeting-get]]
=== 모임 조회

`Get` 요청을 사용해서 기존 목록 중 하나를 조회할 수 있다.

operation::get-meeting[snippets='curl-request,http-response']

[[resources-meeting-update]]
=== 모임 수정

`PUT` 요청을 사용해서 기존 이벤트를 수정할 수 있다.

operation::update-meeting[snippets='request-fields,curl-request,http-response']

[[resources-reservation]]
== 예약
예약을 위한 리소스이다.

[[resources-reservation-list]]
=== 예약 리스트 조회
'GET' 요청을 사용하여 사용자의 예약 목록을 조회한다.

operation::get-reservation-list[snippets='response-fields,curl-request,http-response']

[[resources-reservation-create]]
=== 예약 생성
'POST' 요청을 사용해서 예약을 등록한다.

operation::create-reservation[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[resources-reservation-delete]]
=== 예약 취소

operation::delete-reservation[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']